apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: meportal
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJtZXBvcnRhbDE5OTUuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImFtWnliMmRrYjJOclpYSmpjbVZrT2sxNWJHbG1aVEU1T1RVPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
